In [1]:
import numpy as np
import pandas as pd

In [93]:
#question 1.1
x = [[1,2,3],[4,5,6]]
print(np.array(x))

[[1 2 3]
 [4 5 6]]


In [92]:
#question 1.2
print(np.arange(1,7).reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


In [37]:
#question 1.3
x=np.arange(2,101,2)
print(x)
print("Mean of array x is",x.mean())

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
Mean of array x is 51.0


In [6]:
#question 1.4
x=np.random.random((3,3,3))
print(x)
print("The Minimum value is",x.min())
print("The maximum value is",x.max())

[[[0.93723264 0.3009185  0.19217467]
  [0.25793411 0.32318728 0.80697274]
  [0.30535796 0.88982551 0.39400508]]

 [[0.33308735 0.65801632 0.91004919]
  [0.13921261 0.07016351 0.86666184]
  [0.73383744 0.04945197 0.15705495]]

 [[0.47976483 0.34724887 0.13324979]
  [0.29663523 0.20570783 0.61669942]
  [0.37983348 0.1469244  0.40106437]]]
The Minimum value is 0.049451971318661525
The maximum value is 0.9372326404813552


In [91]:
#question 1.5
print(np.arange(10,22).reshape(3,4))

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [90]:
#question 1.6
start=5
step=3
length=10
end=(length*step)+start
print(end)
print(np.arange(start,end,step))

35
[ 5  8 11 14 17 20 23 26 29 32]


In [46]:
#question 1.7
x=np.random.randint(10, size=(10, 10))
print(x)
memsize=x.itemsize*x.size
print("Memory size of the array is",memsize)

[[8 1 1 7 9 9 3 6 7 2]
 [0 3 5 9 4 4 6 4 4 3]
 [4 4 8 4 3 7 5 5 0 1]
 [5 9 3 0 5 0 1 2 4 2]
 [0 3 2 0 7 5 9 0 2 7]
 [2 9 2 3 3 2 3 4 1 2]
 [9 1 4 6 8 2 3 0 0 6]
 [0 6 3 3 8 8 8 2 3 2]
 [0 8 8 3 8 2 8 4 3 0]
 [4 3 6 9 8 0 8 5 9 0]]
Memory size of the array is 400


In [53]:
#question 1.8
x=np.random.randint(11,size=10)
print("array before change ",x)
x[4]=5
print("array after putting 5 ",x)

array before change  [4 3 9 8 2 0 8 7 7 5]
array after putting 5  [4 3 9 8 5 0 8 7 7 5]


In [89]:
#np.random.randint(1, [6],size=10)

In [55]:
#question 1.9
x=np.arange(10,50)
print("Orginal array",x)
a=np.arange(49,9,-1)
print("Reverse array",a)

Orginal array [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
Reverse array [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [8]:
#question 1.10
np.random.seed(0)
print(np.random.uniform(0,1,size=((3,2))))

[[0.5488135  0.71518937]
 [0.60276338 0.54488318]
 [0.4236548  0.64589411]]


In [87]:
#question 1.11
print(np.zeros((5,5))+ np.arange(5))

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [86]:
#question 1.12
x =np.ones((5,5))
print(x)
print(np.pad(x,pad_width=1))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [54]:
#question 1.13
x=np.diag([1,2,3,4,5])
print(x)
y=np.diag(x)
z=np.diag(y,k=-1)
a,b=np.hsplit(z,[5])
d,e=np.vsplit(a,[5])
print(d)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [85]:
#question 1.14
x =np.ones((10,10))
print(x)
x=x-1
a,b,c=np.hsplit(x,[1,9])
p,q,r=np.vsplit(b,[1,9])
print(np.pad(q,pad_width=1,constant_values=1))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [57]:
#x=np.ones((10,10))
#x[1:-1,1:-1]=0
#x

In [58]:
#question 1.15
np.random.seed(0)
x=np.random.uniform(0,20,20)
print(x)
a=x.astype(int)
print("Using method 1:",a,a.dtype)
b=np.int_(x)
print("Using method 2:",b,b.dtype)

[10.97627008 14.30378733 12.05526752 10.89766366  8.47309599 12.91788226
  8.75174423 17.83546002 19.27325521  7.66883038 15.83450076 10.5778984
 11.36089122 18.51193277  1.42072116  1.74258599  0.40436795 16.65239691
 15.56313502 17.40024296]
Using method 1: [10 14 12 10  8 12  8 17 19  7 15 10 11 18  1  1  0 16 15 17] int32
Using method 2: [10 14 12 10  8 12  8 17 19  7 15 10 11 18  1  1  0 16 15 17] int32


In [62]:
#question 2.1
x=np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
a=np.where(x==1)
c=0
for i in a[0]:
    c=c+1
    if(c==5):
        print("fifth repetition of 1 is:",i)


fifth repetition of 1 is: 8


In [65]:
#question2.2
x=np.arange(1,10)
a,b,c=np.split(x,[4,6])
print("First subarray of 4 size:",a)
print("second subarray of 2 size:",b)
print("third subarray of 3 size:",c)

First subarray of 4 size: [1 2 3 4]
second subarray of 2 size: [5 6]
third subarray of 3 size: [7 8 9]


In [67]:
#question2.3
x = np.arange(16.).reshape((4,4))
print(x)
a,b=np.split(x,[2],axis=1)
print("Left half:")
print(a.astype(int))
print("Right half:")
print(b.astype(int))

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]
Left half:
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
Right half:
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [70]:
#question 2.4
x = np.array([[5,10,15],

 [20,25,30],

 [35,40,45]]
)
print(x)
a,b=np.hsplit(x,[1])
c,d=np.vsplit(b,[2])
print("Print subarray 1:")
print(c)
p,q,r=np.vsplit(a,[1,2])
print("Print subarray 2:",q)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
Print subarray 1:
[[10 15]
 [25 30]]
Print subarray 2: [[20]]


In [84]:
#question 2.5
x = np.array([[ 1,2,3],[ 4,5,6]])
print(x)
y = np.array([[ 7,8,9],[10,11,12]])
print(y)
print(np.concatenate([x,y],axis=1))

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [72]:
#question 2.6
np.random.seed(0)
arr=np.random.randint(11,size=(5,3))
print(arr)
i=0
for i in arr:
    a,arr=np.vsplit(arr,[1])
    print("The min/max of row",i,np.min(a)/np.max(a))
    i=i+1

[[ 5  0  3]
 [ 3  7  9]
 [ 3  5  2]
 [ 4  7  6]
 [ 8  8 10]]
The min/max of row [5 0 3] 0.0
The min/max of row [3 7 9] 0.3333333333333333
The min/max of row [3 5 2] 0.4
The min/max of row [4 7 6] 0.5714285714285714
The min/max of row [ 8  8 10] 0.8


In [69]:
#question2.7
x=np.random.random((5,5))
print("before normalization:")
print(x)
maxi,mini=x.max(),x.min()
x=(x-mini)/(maxi-mini)
print("after normalization")
print(x)

before normalization:
[[0.78364425 0.5000263  0.05037006 0.69909807 0.9923964 ]
 [0.26726254 0.67909062 0.86428144 0.75084425 0.96448977]
 [0.55424244 0.2123905  0.22244322 0.21874937 0.56957353]
 [0.45210904 0.97023668 0.68054469 0.08529557 0.05641833]
 [0.4878377  0.88100456 0.97640439 0.61765792 0.54249878]]
after normalization
[[0.77840094 0.47732873 0.         0.68865167 1.        ]
 [0.23024036 0.66741293 0.86400066 0.74358238 0.97037595]
 [0.53488141 0.17199141 0.1826628  0.17874162 0.55115601]
 [0.42646257 0.97647654 0.66895649 0.03707488 0.0064205 ]
 [0.46439004 0.88175295 0.98302382 0.60219957 0.52241503]]


In [83]:
#question2.8
x=np.arange(3)
print("arr 1:",x)
y=np.arange(3,7)
print("arr 2:",y)
z=np.arange(7,9)
print("arr 3:",z)
print(np.concatenate([x,y,z]))

arr 1: [0 1 2]
arr 2: [3 4 5 6]
arr 3: [7 8]
[0 1 2 3 4 5 6 7 8]


In [76]:
#question2.9
np.random.seed(0)
x=np.random.randint(0,100,size=20)
print(x)
print("Values between 15 and 55 is:")
for i in range(x.size):
    if(x[i]>=15 and x[i]<=55):
        print(x[i])

[44 47 64 67 67  9 83 21 36 87 70 88 88 12 58 65 39 87 46 88]
Values between 15 and 55 is:
44
47
21
36
39
46


In [78]:
#question2.10
a = np.array([1,2,3,2,3,4,3,4,5,6])
print(a)
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(b)
c=np.where(a==b)
print("Position where a and b match are :")
print(c[0])

[1 2 3 2 3 4 3 4 5 6]
[ 7  2 10  2  7  4  9  4  9  8]
Position where a and b match are :
[1 3 5 7]


In [81]:
#question2.11
x=np.arange(20)
print("Original array",x)
for i in range(x.size):
    if (x[i]%2!=0):
        x[i]=-1
print("After replacing odd index values with 1")
print(x)

Original array [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
After replacing odd index values with 1
[ 0 -1  2 -1  4 -1  6 -1  8 -1 10 -1 12 -1 14 -1 16 -1 18 -1]


In [82]:
#question 2.12
x=np.random.randint(10,size=((3,4,3,4)))
print("sum along last two axis is ")
print(x.sum(axis=3).sum(axis=2))

sum along last two axis is 
[[49 47 45 64]
 [54 49 31 49]
 [45 47 50 68]]


In [18]:
np.concatenate?

In [17]:
x = np.arange(20).reshape(4,5)
print(x)
np.hsplit(x,[2,4])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


[array([[ 0,  1],
        [ 5,  6],
        [10, 11],
        [15, 16]]),
 array([[ 2,  3],
        [ 7,  8],
        [12, 13],
        [17, 18]]),
 array([[ 4],
        [ 9],
        [14],
        [19]])]

In [26]:
a= np.arange(0,10)
b=np.arange(11,21)
np.sum(a,b)

TypeError: only integer scalar arrays can be converted to a scalar index

In [29]:
np.linspace?