In [1]:
import numpy as np
import pandas as pd

In [7]:
#Question 1.1
np.random.seed(45)
zeros = np.zeros((10,10))
zeros
generator = np.random.choice(5,3,replace=False)
print(generator)

[1 4 0]


In [8]:
#Question 1.2
np.put(zeros,generator,[6,6,6],mode='raise')
zeros

array([[6., 6., 0., 0., 6., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
#question2
abc=np.zeros(16).reshape(4,4)
print(abc)
abc[0:1,1:2],abc[0:1,3:4],abc[1:2,0:1],abc[1:2,2:3],abc[2:3,1:2],abc[2:3,3:4],abc[3:4,0:1],abc[3:4,2:3]=1,1,1,1,1,1,1,1
print(abc)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


In [14]:
#question3
#With for loop
count=1
for i in range(0,6):
    for j in range(0,6):
        x[i][j]=(i+1)*(j+1)
print (x.astype(int))
#With NumPy Broadcasting
x = np.zeros((6,6))
x = x+np.arange(1,7)
y = np.arange(1,7).reshape(6,1)
z = x*y
z.astype(int)

[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]
 [ 4  8 12 16 20 24]
 [ 5 10 15 20 25 30]
 [ 6 12 18 24 30 36]]


array([[ 1,  2,  3,  4,  5,  6],
       [ 2,  4,  6,  8, 10, 12],
       [ 3,  6,  9, 12, 15, 18],
       [ 4,  8, 12, 16, 20, 24],
       [ 5, 10, 15, 20, 25, 30],
       [ 6, 12, 18, 24, 30, 36]])

In [45]:
#PANDAS

In [14]:
#question1
Alphaindex = ['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z']
df = pd.DataFrame(np.random.randint(1,50,26),Alphaindex)
df.head()

0
A  16
B  18
C   7
D  45
E  43

In [15]:
#question2
data= {'Class1':[1,2,3,4,7,11],
      'Class2':[4,5,6,9,5,0],
      'Class3':[7,5,8,12,1,11]}
df2=pd.DataFrame(data)
print(df2)
my_series=(df2.iloc[0:6,0:1]).unstack()
print(my_series)
type(my_series)

   Class1  Class2  Class3
0       1       4       7
1       2       5       5
2       3       6       8
3       4       9      12
4       7       5       1
5      11       0      11
Class1  0     1
        1     2
        2     3
        3     4
        4     7
        5    11
dtype: int64


pandas.core.series.Series

In [16]:
#question3.1
print(df2)
#1
print(df2.iloc[:,0:2])

   Class1  Class2  Class3
0       1       4       7
1       2       5       5
2       3       6       8
3       4       9      12
4       7       5       1
5      11       0      11
   Class1  Class2
0       1       4
1       2       5
2       3       6
3       4       9
4       7       5
5      11       0


In [19]:
#3.2
print(df2.iloc[3:,:])

   Class1  Class2  Class3
3       4       9      12
4       7       5       1
5      11       0      11


In [20]:
#3.3
print(df2.iloc[:3,:])

   Class1  Class2  Class3
0       1       4       7
1       2       5       5
2       3       6       8


In [23]:
#question4
p1 = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

p2 = pd.Series([8, 9, 10, 11, 12, 7, 6, 5, 4, 3])
eucd=np.absolute(p1-p2)
print(((p1-p2)**2).sum()**0.5)
print(eucd)

18.16590212458495
0    7
1    7
2    7
3    7
4    7
5    1
6    1
7    3
8    5
9    7
dtype: int64


In [32]:
#QUESTION5.1
np.random.seed(42)
index=['a','b','c','d','e','f','g','h','i','j']
column=['p','q','r','s']
df3=pd.DataFrame((np.random.randint(0,100,40).reshape(10,4)),index,column)
print(df3)

    p   q   r   s
a  51  92  14  71
b  60  20  82  86
c  74  74  87  99
d  23   2  21  52
e   1  87  29  37
f   1  63  59  20
g  32  75  57  21
h  88  48  90  58
i  41  91  59  79
j  14  61  61  46


In [33]:
#5.2
# init outputs
nearest_rows = []
nearest_distance = []

# iterate rows.
for i, row in df3.iterrows():
    curr = row
    rest = df3.drop(i)
    e_dists = {}  # init dict to store euclidean dists for current row.
    # iterate rest of rows for current row
    for j, contestant in rest.iterrows():
        # compute euclidean dist and update e_dists
        e_dists.update({j: round(np.linalg.norm(curr.values - contestant.values))})
    # update nearest row to current row and the distance value
    nearest_rows.append(max(e_dists, key=e_dists.get))
    nearest_distance.append(max(e_dists.values()))

df3['nearest_row'] = nearest_rows
df3['dist'] = nearest_distance
df3

p   q   r   s nearest_row  dist
a  51  92  14  71           b   101
b  60  20  82  86           e   115
c  74  74  87  99           d   120
d  23   2  21  52           c   120
e   1  87  29  37           b   115
f   1  63  59  20           c   112
g  32  75  57  21           c    94
h  88  48  90  58           e   115
i  41  91  59  79           d   102
j  14  61  61  46           c    85

In [3]:
#QUESTION6
L = pd.Series(range(15))
def strides(a,stridlen=5 , windowlen=5):
    n= ((a.size-windowlen)//stridlen)+1
    return np.array([a[s:(s+windowlen)] for s in np.arange(0,a.size,stridlen)[:n]])
print(strides(L,stridlen=2,windowlen=4))

[[ 0  1  2  3]
 [ 2  3  4  5]
 [ 4  5  6  7]
 [ 6  7  8  9]
 [ 8  9 10 11]
 [10 11 12 13]]


In [34]:
#7.1
np.random.seed(40)
index=[1,2,3,4]
column=['a','b','c','d','e']
df4=pd.DataFrame((np.random.randint(0,20,20).reshape(4,5)),index,column)
df4

a   b   c   d   e
1   6   7   5  18   1
2  12   7  18  19  10
3  19   9   0  17   9
4   8  15  14   8  10

In [35]:
#7.2
col_list=list(df4.columns)
col_list[2],col_list[0] = col_list[0],col_list[2]
df5=df4[col_list]
df5

c   b   a   d   e
1   5   7   6  18   1
2  18   7  12  19  10
3   0   9  19  17   9
4  14  15   8   8  10

In [36]:
#7.3
def swapcol(x,y,df):
    col_list=list(df.columns)
    x,y = col_list.index(x),col_list.index(y)
    col_list[x],col_list[y] = col_list[y],col_list[x]
    df=df[col_list]
    return df
swapcol('b','d',df4)

a   d   c   b   e
1   6  18   5   7   1
2  12  19  18   7  10
3  19  17   0   9   9
4   8   8  14  15  10

In [37]:
#7.4
df4[df4.columns[::-1]]

e   d   c   b   a
1   1  18   5   7   6
2  10  19  18   7  12
3   9  17   0   9  19
4  10   8  14  15   8

In [38]:
#question8
np.random.seed(100)
ser = pd.Series(np.random.randint(1,10,10), pd.date_range('2000-01-01', periods=10, freq='W-SAT'))
ser

2000-01-01    9
2000-01-08    9
2000-01-15    4
2000-01-22    8
2000-01-29    8
2000-02-05    1
2000-02-12    5
2000-02-19    3
2000-02-26    6
2000-03-04    3
Freq: W-SAT, dtype: int32

In [55]:
#Question9.1
index = pd.DatetimeIndex(['2021-01-01', '2021-01-03',
                          '2021-01-06', '2021-01-08'])
data = pd.Series([1,10,3,np.nan], index=index)
data

2021-01-01     1.0
2021-01-03    10.0
2021-01-06     3.0
2021-01-08     NaN
dtype: float64

In [58]:
#9.2
data.resample('D').fillna(method='ffill').fillna(method='ffill')

2021-01-01     1.0
2021-01-02     1.0
2021-01-03    10.0
2021-01-04    10.0
2021-01-05    10.0
2021-01-06     3.0
2021-01-07     3.0
2021-01-08     3.0
Freq: D, dtype: float64

In [62]:
#Question 10.1
np.random.seed(100)
dict_data = {'Fruits':['Apple','Banana','Orange']*3,
            'Taste': np.random.rand(9),
            'Price': np.random.randint(1,15,9)}
df5=pd.DataFrame(dict_data)
df5

Fruits     Taste  Price
0   Apple  0.543405      9
1  Banana  0.278369      5
2  Orange  0.424518     12
3   Apple  0.844776     13
4  Banana  0.004719     11
5  Orange  0.121569      1
6   Apple  0.670749     12
7  Banana  0.825853     10
8  Orange  0.136707     14

In [77]:
#Question 10.2
(df5.groupby('Fruits')).get_group('Banana')['Taste'].sort_values().iloc[-

0.8258527551050476

In [103]:
#Question 10.3
df5.groupby('Fruits')['Price'].mean().reset_index()

Fruits      Price
0   Apple  11.333333
1  Banana   8.666667
2  Orange   9.000000

In [9]:
def mult_table(n):
    rng = np.arange(1, n+1)
    return rng * rng[:, None]

print(mult_table(6))

[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]
 [ 4  8 12 16 20 24]
 [ 5 10 15 20 25 30]
 [ 6 12 18 24 30 36]]
